### PR TITLE
Add Python3 compatibility

### PR DESCRIPTION
**Pull request by mauritsvanrees**
I am migrating a project from Plone 5.1 to 5.2. One of the custom packages uses `plone.jsonapi.core`. Seems okay on Python 2.7, at least it starts up. I don't think I tried it out for real.

But this does not start up on Python 3, mostly because of relative imports. I have fixed that in the last commit on this `python3` branch. The other commits are easy automatic changes, like code quality commits and using `python-modernize`.

Is anyone still using this package and interested in getting it on Plone 5.2 and Python 3?
I guess we should switch to `plone.restapi`, but if the json api still works, that would be nice.

Note: I have not been able to test it for real: the site does not start up yet due to a few other packages that are not yet Python 3 compatible.

Also, I guess the Travis will fail, even without the changes of this PR. I may not be up to fixing that: I am already struggling too much with Jenkins for core Plone...

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
With these changes, my custom endpoint seems to work fine on Python 3.

**Review by ramonski — APPROVED** [review]

**Comment by ramonski** [comment]
Awesome, thanks @mauritsvanrees!

**Comment by mauritsvanrees** [comment]
Any chance of a release?
I am not in a hurry, but it seems to work.

**Comment by ramonski** [comment]
Yes for sure, going to release as soon as possible. Thanks again.

**Comment by mauritsvanrees** [comment]
A release would be nice.

**Comment by ramonski** [comment]
Version `0.7.0` is released: https://pypi.org/project/plone.jsonapi.core/0.7.0

**Comment by mauritsvanrees** [comment]
Works, thanks!

**Pull request merged**
